include:
  - project: 'infrastructure/shared-workflows'
    ref: master
    file: '/workflows/build/docker-build.yml'

variables:
  DOCKER_REPO_NAME: "external-dns-edgecenter-webhook"

stages:
  - build

docker-build:branch:
  extends: .docker-build

docker-build:master:
  extends: .docker-build
